apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aform-ingress
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: aform-ws-front
                port:
                  number: 80
          - path: /api/user
            pathType: Prefix
            backend:
              service:
                name: aform-was-user
                port:
                  number: 8080
          - path: /api/surveys
            pathType: Prefix
            backend:
              service:
                name: aform-was-survey
                port:
                  number: 3000
          - path: /api/post
            pathType: Prefix
            backend:
              service:
                name: aform-was-post
                port:
                  number: 8080
          - path: /chatbot
            pathType: Prefix
            backend:
              service:
                name: aform-was-ai
                port:
                  number: 5000
---