apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- aform-ingress.yml
- ws-front.yml
- was-user.yml
- was-survey.yml
- was-ai.yml

# if you want to use private docker registry, uncomment this snippet and change the name
# images:
#   - name: chromato99/aform-front-web
#     newName: <private docker registry>/aform-front-web
#   - name: chromato99/aform-service-user
#     newName: <private docker registry>/aform-service-user
#   - name: chromato99/aform-service-survey
#     newName: <private docker registry>/aform-service-survey
#   - name: chromato99/aform-service-ai
#     newName: <private docker registry>/aform-service-ai